/* eslint-disable import/prefer-default-export */
export const DownloaderActions = {
  ADD_TO_DOWNLOAD_QUEUE: 'ADD_TO_DOWNLOAD_QUEUE',
  REMOVE_FROM_DOWNLOAD_QUEUE: 'REMOVE_FROM_DOWNLOAD_QUEUE',
  CLEAR_DOWNLOAD_QUEUE: 'CLEAR_DOWNLOAD_QUEUE',
  CANCEL_DOWNLOAD: 'CANCEL_DOWNLOAD',
  START_DOWNLOAD: 'START_DOWNLOAD',
  DOWNLOAD_FROM_TEXT_FILE: 'DOWNLOAD_FROM_TEXT_FILE',
};
