// eslint-disable-next-line import/prefer-default-export
export enum CONSTANTS {
  DOWNLOAD = 'DOWNLOAD',
  PROGRESS_UPDATE = 'PROGRESS_UPDATE',
  CURRENT_DOWNLOAD_META_DATA = 'CURRENT_DOWNLOAD_META_DATA',
  CANCEL_DOWNLOAD = 'CANCEL_DOWNLOAD',
  PAUSE_DOWNLOAD = 'PAUSE_DOWNLOAD',
  DOWNLOAD_FILE = 'DOWNLOAD_FILE',
}
